package visao;

import com.sun.glass.events.KeyEvent;
import dao.ClienteDao;
import modelo.Cliente;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

public class frmClienteConsulta extends javax.swing.JFrame {

    private static frmClienteConsulta frmConsulta;

    public frmClienteConsulta() {
        initComponents();
    }

    public static frmClienteConsulta getInstancia() {
        if (frmClienteConsulta.frmConsulta == null) {
            frmClienteConsulta.frmConsulta = new frmClienteConsulta();
        }

        return frmClienteConsulta.frmConsulta;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popMenu = new javax.swing.JPopupMenu();
        jmiAlterar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        txtConsulta = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();

        jmiAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/edit.png"))); // NOI18N
        jmiAlterar.setText("Alterar");
        jmiAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAlterarActionPerformed(evt);
            }
        });
        popMenu.add(jmiAlterar);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta de Clientes");
        setPreferredSize(new java.awt.Dimension(600, 400));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Filtro"));

        txtConsulta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtConsultaKeyPressed(evt);
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/search.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscar)
                .addGap(0, 229, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome / Razão", "Sobrenome / Fantasia", "CPF / CNPJ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCliente.setComponentPopupMenu(popMenu);
        jScrollPane1.setViewportView(tblCliente);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        this.searchCliente();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jmiAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAlterarActionPerformed

        if (this.tblCliente.getSelectedRowCount() > 0) {
            int row = this.tblCliente.getSelectedRow();
            int codCliente = (int) this.tblCliente.getValueAt(row, 0);

            frmCliente11.getInstancia().setVisible(true);
            frmCliente11.getInstancia().alterarCliente(codCliente);

            this.setVisible(false);
            this.dispose();
        }
    }//GEN-LAST:event_jmiAlterarActionPerformed

    private void txtConsultaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConsultaKeyPressed
       if(evt.getKeyCode() == KeyEvent.VK_ENTER){
           this.searchCliente();
       }
    }//GEN-LAST:event_txtConsultaKeyPressed

    private void searchCliente() {
        String value = txtConsulta.getText();
        ClienteDao client = new ClienteDao();
        ArrayList<Cliente> listClient = client.consultClient(value);

        Object[] columns = {"Código", "Nome / Razão", "Nome / Fantasia", "CPF / CNPJ"};
        DefaultTableModel model = new DefaultTableModel(new Object[0][0], columns);

        for (Cliente cc : listClient) {
            Object[] obj = new Object[4];
            obj[0] = cc.getCodigo();
            obj[1] = cc.getNome();
            obj[2] = cc.getSobrenome();
            obj[3] = cc.getCpfCnpj();
            model.addRow(obj);
        }

        this.tblCliente.setModel(model);
        this.tblCliente.getColumnModel().getColumn(0).setPreferredWidth(5);
        this.tblCliente.getColumnModel().getColumn(1).setPreferredWidth(100);
        this.tblCliente.getColumnModel().getColumn(2).setPreferredWidth(50);
        this.tblCliente.getColumnModel().getColumn(3).setPreferredWidth(30);
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new frmClienteConsulta().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem jmiAlterar;
    private javax.swing.JPopupMenu popMenu;
    private javax.swing.JTable tblCliente;
    private javax.swing.JTextField txtConsulta;
    // End of variables declaration//GEN-END:variables
}
